

import { Plus_Jakarta_Sans } from "next/font/google";
import { Providers } from './Providers'
import "./globals.css";


const plusJakartaSans  = Plus_Jakarta_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={plusJakartaSans.className}>
      <Providers 
            defaultTheme="system"
            disableTransitionOnChange>
        {children}
      </Providers>
      </body>
    </html>
  );
}
